kind: Metric
apiVersion: capabilities.3scale.hosted.net/v1alpha1
metadata:
  labels:
    api: echo-app
  name: echo-app-metrics
  namespace: 3scale-apimanager
spec:
  description: Counts the number of times an endpoint has been hit
  unit: hit
  incrementHits: true
---
kind: MappingRule
apiVersion: capabilities.3scale.hosted.net/v1alpha1
metadata:
  labels:
    api: echo-app
  name: echo-app-mapping
  namespace: 3scale-apimanager
spec:
  increment: 1
  method: GET
  metricRef:
    name: echo-app-metrics
  path: /echo/{id}
---
kind: Plan
apiVersion: capabilities.3scale.hosted.net/v1alpha1
metadata:
  labels:
    api: echo-app
  name: echo-app-plan
  namespace: 3scale-apimanager
spec:
  approvalRequired: false
  default: true
  costs:
    costMonth: "0"
    setupFee: "0"
  limitSelector:
    matchLabels:
      api: echo-app
  trialPeriod: 0
