
kind: API
apiVersion: capabilities.3scale.hosted.net/v1alpha1
metadata:
  labels:
    environment: production
    api: echo-app
  name: echo-app
  namespace: 3scale-apimanager
spec:
  # No plan selector for this demo
  planSelector:
    matchLabels:
      api: echo-app
  description: "Sample echo application"
  integrationMethod:
    apicastOnPrem:
      apiTestGetRequest: /
      authenticationSettings:
        credentials:
          apiKey:
            authParameterName: user-key
            credentialsLocation: headers
        errors:
          authenticationFailed:
            contentType: text/plain; charset=us-ascii
            responseBody: Authentication failed
            responseCode: 403
          authenticationMissing:
            contentType: text/plain; charset=us-ascii
            responseBody: Authentication Missing
            responseCode: 403
        hostHeader: ""
        secretToken: someThingIShouldReplaceLater1234
      mappingRulesSelector:
        matchLabels:
          api: echo-app
      privateBaseURL: https://echo-api.3scale.net:443
      stagingPublicBaseURL: https://apicast-dev-api-dev.apps.cluster-nyc-3c57.nyc-3c57.example.opentlc.com:443
      productionPublicBaseURL: https://apicast-dev-api-dev.apps.cluster-nyc-3c57.nyc-3c57.example.opentlc.com:443
  metricSelector:
    matchLabels:
      api: echo-app
