---

apiVersion: capabilities.3scale.net/v1alpha1
kind: API
metadata:
  labels:
    environment: production
  name: echo-app
  namespace: 3scale
spec:
  # No plan selector for this demo
  planSelector:
    matchLabels:
      api: echo-app
  description: Sample application that Echos responses
  integrationMethod:
    apicastOnPrem:
      apiTestGetRequest: /
      authenticationSettings:
        credentials:
          apiKey:
            authParameterName: user-key
            credentialsLocation: headers
        errors:
          authenticationFailed:
            contentType: text/plain; charset=us-ascii
            responseBody: Authentication failed
            responseCode: 403
          authenticationMissing:
            contentType: text/plain; charset=us-ascii
            responseBody: Authentication Missing
            responseCode: 403
        hostHeader: ""
        secretToken: MySecretTokenBetweenApicastAndMyBackend_1237120312
      mappingRulesSelector:
        matchLabels:
          api: echo-app
      privateBaseURL: https://echo-api.3scale.net:443
      productionPublicBaseURL: https://api-3scale-apicast-production.apps-crc.testing:443
      stagingPublicBaseURL: https://api-3scale-apicast-staging.apps-crc.testing:443
  metricSelector:
    matchLabels:
      api: echo-app
