apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: example-apimanager
spec:
  wildcardDomain: apps.cluster-nyc-6b8f.nyc-6b8f.example.opentlc.com
  resourceRequirementsEnabled: false
