kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 3scale-operator
subjects:
- kind: ServiceAccount
  name: 3scale-operator
  namespace: 3scale-operator-custom
roleRef:
  kind: ClusterRole
  name: 3scale-operator-custom
  apiGroup: rbac.authorization.k8s.io
