apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: threescale-operator
  template:
    metadata:
      labels:
        name: threescale-operator
    spec:
      serviceAccountName: 3scale-operator
      containers:
        - name: 3scale-operator
          image: quay.io/kjanania/3scale-bof-summit-2020:summit-2.7
          command:
            - 3scale-operator
          imagePullPolicy: Always
          env:
            # - name: WATCH_NAMESPACE
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.namespace
            # Set to "" to watch all namespaces
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "threescale-operator"
            - name: BACKEND_IMAGE
              value: "registry.redhat.io/3scale-amp2/backend-rhel7:3scale2.7"
            - name: APICAST_IMAGE
              value: "registry.redhat.io/3scale-amp2/apicast-gateway-rhel7:3scale2.7"
            - name: SYSTEM_IMAGE
              value: "registry.redhat.io/3scale-amp2/system-rhel7:3scale2.7"
            - name: ZYNC_IMAGE
              value: "registry.redhat.io/3scale-amp2/zync-rhel7:3scale2.7"
            - name: SYSTEM_MEMCACHED_IMAGE
              value: "registry.redhat.io/3scale-amp2/memcached-rhel7:3scale2.7"
